### ISSUE TITLE
Should accept naked values as strings

### ISSUE THREAD

**Issue by houshuang** [ewildgoose/elixir-xml_rpc#1]
I don't know if this is part of the official spec, but some APIs return value's not wrapped in a value type. These should be interpreted as strings (the Python XML-RPC library at least does this). Here's an example response from the Confluence wiki:

``` elixir
iex(1)> XMLRPC.decode("<?xml version=\"1.0\"?><methodResponse><params><param><value>a4sdfff7dad8</value></param></params></methodResponse>")
{:error, 'Missing element before end-tag: value'}
```

**Comment by houshuang** [comment]
:bump

**Comment by ewildgoose** [comment]
I just pushed version 0.6.  Can you please see if this now correctly parses your input?

It seems that the spec allows you to omit the value specifier tag (why!?), which is somewhat challenging to express in xml schema... Version 0.6 should allow the type specifier to now be optional and it defaults to text if omitted. 

That said, I don't see why anyone should chose to implement their API to take advantage of this loophole... Sigh...

**Comment by houshuang** [comment]
Thank you very much, it works perfectly. And just in time for me. I agree with you on the silliness, but at least now I can interact with this API.
