### ISSUE TITLE
Parsing of XML with empty struct fails

### ISSUE THREAD

**Issue by albertored** [ewildgoose/elixir-xml_rpc#10]
My interpretation of the XML-RPC specifications is that `struct` tags can be empty and indeed it happened to me of retrieving XML-RPC responses with empty `struct` tags.

Parsing such responses with this library gives an error from `erlsom` because the `xsd` template does not allow this. Also fixing the template your library gives another error

I have done a very small patch to handle this situation, if you want I can submit a pull request

**Comment by ewildgoose** [comment]
Yes, please send pull request(s). Ideally break up the commits. Thanks for noticing this!

**Comment by ewildgoose** [comment]
Merged, thanks
