### ISSUE TITLE
Running tests on travis-ci

### ISSUE THREAD

**Issue by h4cc** [ewildgoose/elixir-xml_rpc#3]
Maybe plz?

**Comment by ewildgoose** [comment]
Forgive my ignorance, but I'm not sure what I need to do here? Can you give me a leg up?

**Comment by h4cc** [comment]
To run your tests on travis, you need to create a `.travis.yml` file.
Example for that: https://github.com/h4cc/slugger/blob/master/.travis.yml
After doing so, you need to connect this repo to travis at https://travis-ci.org/

After that, travis will run `mix test` after each change to the repo. Also a cool build status badge will be available then :)

**Comment by ewildgoose** [comment]
Thanks for your advice!  Now added to travis and pushed new release to hex!

Could the project be added to your awesome-elixir list perhaps? (I think also "elixir_priority_queue" and "elixir-primes" would be of interest..?)

**Comment by h4cc** [comment]
@ewildgoose Thanks for that hint, will add your suggestions then :dancer:
